open ContainersLabels

type t = Parser.token

let to_string t =
  let open Parser in
  match t with
  | WHILE -> "while"
  | TRUE -> "true"
  | THIS -> "this"
  | SUPER -> "super"
  | STRING str -> "STRING(\"" ^ str ^ "\")"
  | STAR -> "*"
  | SLASH -> "/"
  | SEMICOLON -> ";"
  | RIGHT_PAREN -> "("
  | RIGHT_BRACE -> ")"
  | RETURN -> "return"
  | PLUS -> "+"
  | OR -> "or"
  | NUMBER num -> "NUMBER(" ^ Float.to_string num ^ ")"
  | NIL -> "nil"
  | MINUS -> "-"
  | LOG -> "log"
  | LET -> "let"
  | LESS_EQUAL -> "<="
  | LESS -> "<"
  | LEFT_PAREN -> "("
  | LEFT_BRACE -> "{"
  | IF -> "if"
  | IDENTIFIER id -> "ID(" ^ id ^ ")"
  | GREATER_EQUAL -> ">="
  | GREATER -> ">"
  | FOR -> "for"
  | FALSE -> "false"
  | EQUAL_EQUAL -> "=="
  | EQUAL -> "="
  | EOF -> "<EOF>"
  | ELSE -> "else"
  | DOT -> "."
  | DEFN -> "defn"
  | COMMA -> ","
  | CLASS -> "class"
  | BANG_EQUAL -> "!="
  | BANG -> "!"
  | AND -> "and"
